/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    FavoriteButton: typeof import('./src/components/FavoriteButton.vue')['default']
    FavoriteStarButton: typeof import('./src/components/FavoriteStarButton.vue')['default']
    FilmCard: typeof import('./src/components/FilmCard.vue')['default']
    FilmsList: typeof import('./src/components/FilmsList.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    WishlistButton: typeof import('./src/components/WishlistButton.vue')['default']
  }
}
