/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FavoriteButton: typeof import('./src/components/FavoriteButton.vue')['default']
    FavoritesButton: typeof import(./src/components/FavoriteButton.vueue')['default']
    FavotiteButton: typeof import('./src/components/FavotiteButton.vue')['default']
    FilmCard: typeof import('./src/components/FilmCard.vue')['default']
    FilmsList: typeof import('./src/components/FilmsList.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WhishlistButton: typeof import('./src/components/WishlistButton.vue')['default']
    WishlistButton: typeof import('./src/components/WishlistButton.vue')['default']
  }
}
